stages:
  diet_recommendation_data_ingestion:
    cmd: python src/Healthyai/pipeline/stage_01_diet_recomd_data_ingestion.py
    deps:
      - src/Healthyai/pipeline/stage_01_diet_recomd_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/diet_recomendation/data_ingestion

  diet_recommendation_data_validation:
    cmd: python src/Healthyai/pipeline/stage_02_diet_recomd_data_validation.py
    deps:
      - src/Healthyai/pipeline/stage_02_diet_recomd_data_validation.py
      - config/config.yaml
      - schema.yaml
    outs:
      - artifacts/diet_recomendation/data_validation

  diet_recommendation_model_trainer:
    cmd: python src/Healthyai/pipeline/stage_03_diet_recomd_model_trainer.py
    deps: 
      - src/Healthyai/pipeline/stage_03_diet_recomd_model_trainer.py
      - artifacts/diet_recomendation/data_ingestion/diet_recommendation.csv
    params:
        - KMeans
    outs:
      - artifacts/diet_recomendation/model_trainer

  food_image_data_ingestion:
    cmd: python src/Healthyai/pipeline/stage_04_food_classifi_data_ingestion.py
    deps:
      - src/Healthyai/pipeline/stage_04_food_classifi_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/food_image_classification/data_ingestion/food classification

  food_image_prepare_base_model:
    cmd:  python src/Healthyai/pipeline/stage_05_food_classifi_prebasemodel.py
    deps: 
      - src/Healthyai/pipeline/stage_05_food_classifi_prebasemodel.py
      - config/config.yaml
    params:
      - VGG16
    outs:
      - artifacts/food_image_classification/prepare_base_model

  food_image_model_training:
    cmd: python src/Healthyai/pipeline/stage_06_food_classifi_training.py
    deps:
      - src/Healthyai/pipeline/stage_06_food_classifi_training.py
      - config/config.yaml
      - artifacts/food_image_classification/data_ingestion/food classification
      - artifacts/food_image_classification/prepare_base_model
    params:
      - VGG16
    outs:
      - artifacts/food_image_classification/training

  food_image_model_evaluation:
    cmd: python src/Healthyai/pipeline/stage_07_food_classifi_evaluation.py
    deps:
      - src/Healthyai/pipeline/stage_07_food_classifi_evaluation.py
      - config/config.yaml
      - artifacts/food_image_classification/data_ingestion/food classification
      - artifacts/food_image_classification/training/model.h5

    params:
      - VGG16
    metrics:
    - scores.json:
        cache: false


  

  

  
