# Generated by Django 4.2.10 on 2024-02-15 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceapp', '0003_alter_dietrecommendation_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecommendation',
            name='goal',
            field=models.CharField(choices=[('WeightLoss', 'WeightLoss'), ('WeightGain', 'WeightGain'), ('MaintainWeight', 'MaintainWeight')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietRecommendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
