artifacts: artifacts

# Diet Recommendation

diet_recommendation_data_ingestion:
  root_dir: artifacts/diet_recomendation/data_ingestion
  source_URL: https://drive.google.com/file/d/1dOGy_vMtQU3YqETamp2CNo78w8-ckLWN/view?usp=drive_link
  local_data_file: artifacts/diet_recomendation/data_ingestion/data.zip
  unzip_dir: artifacts/diet_recomendation/data_ingestion

diet_recommendation_data_validation:
  root_dir: artifacts/diet_recomendation/data_validation
  unzip_data_dir: artifacts/diet_recomendation/data_ingestion/diet_recommendation.csv
  STATUS_FILE: artifacts/diet_recomendation/data_validation/status.txt

diet_recommendation_model_trainer:
  root_dir: artifacts/diet_recomendation/model_trainer
  data_path: artifacts/diet_recomendation/data_ingestion/diet_recommendation.csv
  model_name: model.joblib

#Food image classification

food_image_data_ingestion:
  root_dir: artifacts/food_image_classification/data_ingestion
  source_URL: https://drive.google.com/file/d/1lky7C3LipwPKv46QEjpTVHDTfrxEtXew/view?usp=drive_link
  local_data_file: artifacts/food_image_classification/data_ingestion/data.zip
  unzip_dir:  artifacts/food_image_classification/data_ingestion

food_image_prepare_base_model:
  root_dir: artifacts/food_image_classification/prepare_base_model
  base_model_path: artifacts/food_image_classification/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/food_image_classification/prepare_base_model/base_model_updated.h5
  
