artifacts: artifacts

diet_recommendation_data_ingestion:
  root_dir: artifacts/diet_recomendation/data_ingestion
  source_URL: https://drive.google.com/file/d/1aPJGmUjLxqHMtphSjz1XjyeTer0PtMOJ/view?usp=drive_link
  local_data_file: artifacts/diet_recomendation/data_ingestion/data.zip
  unzip_dir: artifacts/diet_recomendation/data_ingestion

