# Generated by Django 5.0 on 2024-02-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecommendservices',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
