# Generated by Django 5.0 on 2024-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0002_alter_dietrecommendservices_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecommendservices',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dietrecommendservices',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
